#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahavrius <ahavrius@student.unit.ua>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/19 18:30:30 by ahavrius          #+#    #+#              #
#    Updated: 2018/09/19 18:36:37 by ahavrius         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file
FLAGS = -Wall -Wextra -Werror
FILE = display_file.c
OBJECT = display_file.o

all: $(NAME)

$(NAME) :
	gcc $(FLAGS) -o $(NAME) $(FILE)

clean:
	/bin/rm -f $(OBJECT)

fclean: clean
	/bin/rm -f $(NAME)